CREATE TABLE appointments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	pet_id INTEGER NOT NULL,
	client_id INTEGER NOT NULL,
	reason TEXT(255) NOT NULL,
	appt_time DATETIME NOT NULL,
	duration INTEGER DEFAULT 0 NOT NULL,
	comments TEXT(255)
);